### ISSUE TITLE
Feature Request: Adding ViSQOL/MOS scores for audio quality measurements

### ISSUE THREAD

**Issue by suyash-ls** [vpalmisano/webrtcperf#124]
Currently, the utility allows us to observe the Inbound and Outbound audio stats. **ViSQOL/MOS** will allow the developers and teams to understand the audio performance of their application against a objective score.

**ViSQOL** - Perceptual Quality Estimator for speech and audio (https://github.com/google/visqol)

I've been using manually compiled binary of ViSQOL to obtain the performance of my platform. Having this as part of WebRTCPerf would be very convenient.

**Comment by vpalmisano** [comment]
Done: https://github.com/vpalmisano/webrtcperf/commit/e9b515578248384616022c715450bcaac7eddd08
