### ISSUE TITLE
Feature Request: Support for Network.emulateNetworkConditions

### ISSUE THREAD

**Issue by salzig** [vpalmisano/webrtcperf#127]
Hej, 
would be nice to have support for `Network.emulateNetworkConditions` https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions . It would allow to throttle the network connection without the need to give permission to Network Configuration on the host system when run within a container.

**Comment by vpalmisano** [comment]
Unfortunately that limits are only applied to the http traffic, the WebRTC connections are unaffected by the browser emulated networking.

**Comment by salzig** [comment]
Interesting ~, is HTTP3 also a Problem?~. 

TIL: Looks like the support is only available to HTTP(s)(1,2,3) and WebSockets. But not WebRTC.
