### ISSUE TITLE
Are you open to PR to expose more functions

### ISSUE THREAD

**Issue by salzig** [vpalmisano/webrtcperf#130]
Hej, 
are you open to PR to expose more Puppeteer functions? 

I have to test a page that unfortunately ignores direct DOM manipulation, so I have to use `keypressText` to input Text and need additional functions like `page.click` to interact with that page.

**Comment by salzig** [comment]
just created #131 cause I need it.

**Comment by vpalmisano** [comment]
Thanks, merged
