### ISSUE TITLE
Unable to get saveSendVideoTrack with Jitsi-Meet

### ISSUE THREAD

**Issue by daimoc** [vpalmisano/webrtcperf#168]
Hi Vittorio,
First of all, I want to give you a big thanks for creating and maintaining this amazing tool for WebRTC performance and quality evaluation. It's been incredibly helpful in our work, and I deeply appreciate the effort you've put into building and sharing it with the community.

I’ve encountered an issue while using the VMAF calculator scenario for Jitsi-Meet :

**Issue Description**
When I run the first part of the test to get the sender and receiver video, I only get the received video and not the sender one.

I run my test with the latest docker version and this command : 

>  docker run -it --rm \
>     --net=host \
>      -v /dev/shm:/dev/shm \
>     -v $PWD/data:/data \
>     -e DEBUG_LEVEL=DEBUG \
>     ghcr.io/vpalmisano/webrtcperf:devel \
>     --url=[https://$JITSI_SERVER/$ROOM#config.prejoinConfig.enabled=false](about:blank) \
>     --sessions=2 \
>     --tabs-per-session=1 \
>     --show-page-log=true \
>     --video-duration=30 \
>     --script-params="{timestampWatermarkVideo:true,saveSendVideoTrack:'0',saveRecvVideoTrack:'1'}" \
>     --server-port=5000 \
>     --server-use-https=true \
>     --server-data=/data \
>     --run-duration=90

At the test end, I only get the file "Participant-000001_recv_remote-video-1.ivf.raw" in my result folder, it seems the saveSendVideoTrack doesn't work with Jitsi.  
Do you have some idea to enable this feature with Jitsi ?  

Once again, thank you for your incredible work—this tool is really great for those working with WebRTC.
Looking forward to your response.
Best regards,
Damien Fétis

**Comment by vpalmisano** [comment]
Thanks for reporting it!
It should be fixed with this change: https://github.com/vpalmisano/webrtcperf/commit/1eeb46bfdb826e52a2685f0c862c96d25adff5d1
