### ISSUE TITLE
Throttle config does not work

### ISSUE THREAD

**Issue by Dev-Mikko** [vpalmisano/webrtcperf#5]
Hi. I have found a problem linked to `throttleConfig` option. When I use it, the shell shows me the following error: `Error: You need to at least set one of up/down/rtt.`

I think that there is a parsing problem.

I used the same input string used in the CONFIG.MD file. I am working with Docker on Debian 10. I am using the command `sudo modprobe ifb numifbs=1` before to run the container. The `--cap-add=NET_ADMIN` option has been also added to the docker run command.

I tried different string formats but there is no way to use this command.

**Comment by vpalmisano** [comment]
Fixed with https://github.com/vpalmisano/webrtc-stress-test/commit/f0b42369ab016567b35bece4a89851a8f697d47b
