### ISSUE TITLE
Feature Request: Allow dynamic URL generation in webrtcperf

### ISSUE THREAD

**Issue by Mkots** [vpalmisano/webrtcperf#60]
Currently, the webrtcperf program accepts a static URL through the --url parameter. This limitation makes it difficult to use dynamic, calculated URLs for specific test scenarios.

I propose adding a new command-line parameter --customUrlHandler that accepts a path to a JavaScript file. This file should contain a function that generates a URL based on the input parameters.

For example, the JavaScript file (`handler.mjs`) may look like this:
```js
export default function ({
  id,
  sessions,
  tabIndex,
  tabsPerSession,
  index,
  pid,
}) {
  return `https://example.com/${id}/${sessions}/${tabIndex}/${tabsPerSession}/${index}/${pid}`
}
```
The main program should import this function and use it to generate the URLs based on the input parameters.

An alternative solution could be to pass a JSON object with a URL pattern as the --url parameter. However, this would require modifying the current implementation and could limit the flexibility of the URL generation.

This feature will enable users to generate dynamic URLs for various test scenarios, providing more flexibility in the testing process.

**Comment by vpalmisano** [comment]
Did you tried the `--url-query` option described here https://vpalmisano.github.io/webrtcperf/types/Config.html#$urlquery?
Probably we can use use a similar approach for the `--url` option, using template variables.

**Comment by Mkots** [comment]
Yeah, I've seen `--url-query` but in my case, I need several completely different URLs for "hosts" and for "participants" e.g. 
`https://school.com/teacher/${teacher_name}/class/math/${1}`
`https://school.com/student/${student_name}/math/lesson/${1}` 
So it needs custom logic to generate such URLs.
Ofc, I can use some sort of proxy to do it, but it's not as convenient as an "in-box solution"
